export {default as HomePage} from './HomePage/ui/HomePage/HomePage'
export {default as ProfilePage} from './ProfilePage/ui/ProfilePage/ProfilePage'
export {default as InstallmentPage} from './InstallmentPage/ui/InstallmentPage/InstallmentPage'
export {default as NotFoundPage} from './NotFoundPage/ui/NotFoundPage'
export {default as NewsPage} from './NewsPage/ui/NewsPage/NewsPage'
export {default as NewsDetailPage} from './NewsDetailPage/ui/NewsDetailPage/NewsDetailPage'